[versions]
android-gradle = "8.4.2"
androidx-activity-compose = "1.9.0"
androidx-core = "1.13.1"
androidx-documentfile = "1.1.0-alpha01"
androidx-preference = "1.2.1"
bugsnag-android = "6.6.1"
bugsnag-gradle = "0.1.0"
bugsnag-jvm = "3.7.1"
buildkonfig-gradle = "0.15.1"
compose = "1.7.0-dev1731"
conveyor = "1.10"
desugar_jdk_libs = "2.0.4"
flatlaf = "3.4.1"
google-material = "1.13.0-alpha04"
jna = "5.14.0"
jsystemthemedetector = "7dde337429"
korlibs = "6.0.0-alpha9"
korlibs-csv = "6.0.0-alpha2"
kotlin = "2.0.20-Beta2"
kotlinx-coroutines = "1.9.0-RC"
kotlinx-datetime = "0.6.0"
kotlinx-serialization = "1.7.1"
ksoup = "0.1.2"
ktor = "2.3.12"
moko-resources = "0.24.1"
multiplatform-settings = "1.1.1"
okio = "3.9.0"
oshi = "6.6.1"
richeditorCompose = "1.0.0-rc05-k2"
slf4j = "2.1.0-alpha1"
windowStyler = "cad9442ec3"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "androidx-documentfile" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }
bugsnag-android = { module = "com.bugsnag:bugsnag-android", version.ref = "bugsnag-android" }
bugsnag-jvm = { module = "com.bugsnag:bugsnag", version.ref = "bugsnag-jvm" }
compose-material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref="compose" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
flatlaf = { module = "com.formdev:flatlaf", version.ref = "flatlaf" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
jsystemthemedetector = { module = "com.github.zacharee:jSystemThemeDetector", version.ref = "jsystemthemedetector" }
korlibs-io = { module = "com.soywiz:korlibs-io", version.ref = "korlibs" }
korlibs-platform = { module = "com.soywiz:korlibs-platform", version.ref = "korlibs" }
korlibs-serialization-csv = { module = "com.soywiz:korlibs-serialization-csv", version.ref = "korlibs-csv" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
moko-resources = { module = "dev.icerock.moko:resources", version.ref = "moko-resources" }
moko-resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko-resources" }
multiplatformSettings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatformSettings-noArg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatform-settings" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshi" }
richeditor-compose = { module = "com.mohamedrejeb.richeditor:richeditor-compose", version.ref = "richeditorCompose" }
slf4j = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
window-styler = { module = "com.github.zacharee.ComposeWindowStyler:window-styler", version.ref = "windowStyler" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
bugsnag-gradle = { id = "com.bugsnag.gradle", version.ref = "bugsnag-gradle" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig-gradle" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
conveyor = { id = "dev.hydraulic.conveyor", version.ref = "conveyor" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
moko-resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko-resources" }
