[versions]
android-gradle = "8.13.0"
androidx-activity-compose = "1.11.0"
androidx-core = "1.17.0"
androidx-documentfile = "1.1.0"
androidx-performance-annotation = "1.0.0-alpha01"
androidx-preference = "1.2.1"
bugsnag-android = "6.18.0"
bugsnag-gradle = "1.0.0"
bugsnag-jvm = "3.8.0"
buildkonfig-gradle = "0.17.1"
compose = "1.10.0+dev2995"
compose-hot-reload = "1.0.0-beta09"
composedialog = "0.2.1"
conveyor = "1.12"
conveyor-control = "1.1"
cryptography = "0.5.0"
csv = "1.1"
desugar_jdk_libs = "2.1.5"
filekit = "0.11.0"
flatlaf = "3.6.1"
githubApi = "2.0-rc.5"
google-material = "1.14.0-alpha05"
jna = "5.18.0"
jsystemthemedetector = "7dde337429"
kmpfile = "0.8.0"
kmpplatform = "0.1.0"
kotlin = "2.2.10"
kotlinx-atomicfu = "0.29.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
kotlinx-serialization = "1.9.0"
kotlinxCryptoCrc32 = "0.0.4"
ksoup = "0.2.5"
ktor = "3.3.0"
material-icons-core = "1.7.3"
materialyou = "0.2.9"
moko-resources = "0.25.0"
multiplatform-settings = "1.3.0"
nserrorKt = "0.2.0"
nsexceptionKt = "1.0.4"
nsexceptionKtBugsnag = "1.0.0-BETA-11"
oshi = "6.9.0"
richeditorCompose = "1.0.0-rc13"
semver = "3.0.0"
slf4j = "2.0.17"
vaqua = "13"
windowStyler = "0.3.3-20250226.143418-11"
xmlbuilder = "0.2.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "androidx-documentfile" }
androidx-performance-annotation = { module = "androidx.performance:performance-annotation", version.ref = "androidx-performance-annotation" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }
bugsnag-android = { module = "com.bugsnag:bugsnag-android", version.ref = "bugsnag-android" }
bugsnag-jvm = { module = "com.bugsnag:bugsnag", version.ref = "bugsnag-jvm" }
conveyor-control = { module = "dev.hydraulic.conveyor:conveyor-control", version.ref = "conveyor-control" }
cryptography-core = { module = "dev.whyoleg.cryptography:cryptography-core", version.ref = "cryptography" }
cryptography-provider-jdk = { module = "dev.whyoleg.cryptography:cryptography-provider-jdk", version.ref = "cryptography" }
cryptography-provider-openssl3-prebuilt = { module = "dev.whyoleg.cryptography:cryptography-provider-openssl3-prebuilt", version.ref = "cryptography" }
csv = { module = "de.halfbit:csv", version.ref = "csv" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugar_jdk_libs" }
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }
flatlaf = { module = "com.formdev:flatlaf", version.ref = "flatlaf" }
github-api = { module = "org.kohsuke:github-api", version.ref = "githubApi" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
jsystemthemedetector = { module = "com.github.zacharee:jSystemThemeDetector", version.ref = "jsystemthemedetector" }
kmpfile = { module = "dev.zwander:kmpfile", version.ref = "kmpfile" }
kmpplatform = { module = "dev.zwander:kmpplatform", version.ref = "kmpplatform" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-crypto-crc32 = { module = "io.github.andreypfau:kotlinx-crypto-crc32", version.ref = "kotlinxCryptoCrc32" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "material-icons-core" }
moko-resources = { module = "dev.icerock.moko:resources", version.ref = "moko-resources" }
moko-resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko-resources" }
nserrorKt = { module = "com.rickclephas.kmp:nserror-kt", version.ref = "nserrorKt" }
nsexceptionKt-bugsnag = { module = "com.rickclephas.kmp:nsexception-kt-bugsnag", version.ref = "nsexceptionKtBugsnag" }
nsexceptionKt-core = { module = "com.rickclephas.kmp:nsexception-kt-core", version.ref = "nsexceptionKt" }
multiplatformSettings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatformSettings-noArg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatform-settings" }
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshi" }
richeditor-compose = { module = "com.mohamedrejeb.richeditor:richeditor-compose", version.ref = "richeditorCompose" }
semver = { module = "io.github.z4kn4fein:semver", version.ref = "semver" }
slf4j = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
vaqua = { module = "org.violetlib:vaqua", version.ref = "vaqua" }
window-styler = { module = "com.mayakapps.compose:window-styler", version.ref = "windowStyler" }
xmlbuilder = { module = "dev.zwander:xmlbuilder", version.ref = "xmlbuilder" }
zwander-composedialog = { module = "dev.zwander:composedialog", version.ref = "composedialog" }
zwander-materialyou = { module = "dev.zwander:materialyou", version.ref = "materialyou" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
bugsnag-gradle = { id = "com.bugsnag.gradle", version.ref = "bugsnag-gradle" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig-gradle" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload" }
conveyor = { id = "dev.hydraulic.conveyor", version.ref = "conveyor" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
moko-resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko-resources" }
